[project]
name = "code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.0, <3.13"
dependencies = [
    "Django~=4.2",
    "gunicorn~=23.0",
    "djangorestframework~=3.15",
    "apscheduler~=3.11",
]

[dependency-groups]
dev = [
    "pytest-django~=4.10",
    "pytest-mock~=3.14",
    "pytest-cov~=6.0",
    "ruff~=0.9",
    "jupyter~=1.1",
    "jupyterlab-language-pack-ja-jp~=4.3",
    "folium~=0.19",
    "skyfield~=1.50",
]
